/**
 * Common types used across VALR API
 */

/**
 * Order side (buy or sell)
 */
export type OrderSide = 'BUY' | 'SELL';

/**
 * Order type
 */
export type OrderType =
  | 'MARKET'
  | 'LIMIT'
  | 'STOP_LOSS_LIMIT'
  | 'TAKE_PROFIT_LIMIT';

/**
 * Time in force for orders
 */
export type TimeInForce =
  | 'GTC'  // Good Till Cancelled
  | 'IOC'  // Immediate Or Cancel
  | 'FOK'; // Fill Or Kill

/**
 * Order status
 */
export type OrderStatus =
  | 'PLACED'
  | 'PARTIALLY_FILLED'
  | 'FILLED'
  | 'CANCELLED'
  | 'FAILED'
  | 'PENDING';

/**
 * Post-only order behavior
 */
export type PostOnly =
  | 'POST_ONLY_REPRICE'
  | 'POST_ONLY_REJECT'
  | 'NOT_POST_ONLY';

/**
 * Transaction type
 */
export type TransactionType =
  | 'LIMIT_BUY'
  | 'LIMIT_SELL'
  | 'MARKET_BUY'
  | 'MARKET_SELL'
  | 'SIMPLE_BUY'
  | 'SIMPLE_SELL'
  | 'DEPOSIT'
  | 'WITHDRAWAL'
  | 'BLOCKCHAIN_RECEIVE'
  | 'BLOCKCHAIN_SEND'
  | 'FIAT_DEPOSIT'
  | 'FIAT_WITHDRAWAL'
  | 'REFERRAL_REBATE'
  | 'REFERRAL_REWARD'
  | 'PROMOTIONAL_REBATE'
  | 'INTERNAL_TRANSFER'
  | 'STAKING_REWARD'
  | 'INTEREST_PAYMENT';

/**
 * Currency code (e.g., BTC, ETH, ZAR, USDC)
 */
export type CurrencyCode = string;

/**
 * Currency pair (e.g., BTCZAR, ETHUSDC)
 */
export type CurrencyPair = string;

/**
 * Network type for crypto deposits/withdrawals
 */
export type NetworkType = string;

/**
 * Cryptocurrency address
 */
export type CryptoAddress = string;

/**
 * Currency pair type
 */
export type PairType = 'SPOT' | 'FUTURES';

/**
 * Pagination parameters
 */
export interface PaginationParams {
  /** Number of records to skip */
  skip?: number;
  /** Maximum number of records to return */
  limit?: number;
}

/**
 * Pagination parameters with beforeId
 */
export interface CursorPaginationParams {
  /** ID to paginate before */
  beforeId?: string;
  /** Maximum number of records to return */
  limit?: number;
}

/**
 * Time range filter
 */
export interface TimeRangeParams {
  /** Start time (ISO 8601 format) */
  startTime?: string;
  /** End time (ISO 8601 format) */
  endTime?: string;
}

/**
 * Price and quantity
 */
export interface PriceQuantity {
  /** Price per unit */
  price: string;
  /** Quantity */
  quantity: string;
}

/**
 * Order book entry
 */
export interface OrderBookEntry {
  /** Order side */
  side: OrderSide;
  /** Quantity */
  quantity: string;
  /** Price */
  price: string;
  /** Currency pair */
  currencyPair: CurrencyPair;
  /** Number of orders at this price level */
  orderCount: number;
}

/**
 * Customer order ID (optional unique identifier provided by customer)
 */
export type CustomerOrderId = string;

/**
 * Internal order ID (generated by VALR)
 */
export type OrderId = string;

/**
 * Subaccount ID
 */
export type SubaccountId = string;

/**
 * ISO 8601 timestamp string
 */
export type ISOTimestamp = string;

/**
 * Conditional order trigger type
 */
export type ConditionalOrderTriggerType =
  | 'MARK_PRICE'
  | 'LAST_TRADED_PRICE';

/**
 * Stop loss or take profit order type
 */
export type ConditionalOrderType =
  | 'STOP_LOSS'
  | 'TAKE_PROFIT';

/**
 * Batch order status
 */
export type BatchOrderStatus =
  | 'ACCEPTED'
  | 'FAILED';
